### ISSUE TITLE
MacOSX(Yosemite)のSublimeText3のエラー報告

### ISSUE THREAD

**Issue by wildwest-service** [codic-project/codic-sublime-plugin#1]
はじめまして！codicのSublime Text用プラグインがリリースされるのを楽しみにしていました。

Mac OSX(Yosemite)のSublimeText3で見つけたエラー内容をご報告いたします。
- letter_caseが反映されない
  - `Sublime Text 3 > Packages > User > CodicCommands.sublime-settings`内では`"letter_case": "camel"`となっている。
- Generate namingを実行した際に「Failed to call API, due to : text は必須です」と表示される
  - エディタ内で文字列選択した状態でGenerate namingをした場合は表示されない

**Comment by kenji-namba** [comment]
バグ報告、ありがとう！

> Generate namingを実行した際に ...

修正しました。

> letter_caseが反映されない

については、こちらの環境 (OS X Mountain Lion) では再現しませんでしたので、詳細な手順を教えて頂けますでしょうか。

**Comment by wildwest-service** [comment]
対応ありがとうございます！ Generate namingに関するエラーが解消された後、再現しなくなりましたので、そこに起因するものだったのかもしれません。

手順としては次の通りでした。
1. 「ツール > コマンドパレット > Codic: Generate Naming」または「Shift + cmd + D」にて、Text to generate [ja]を表示
2. 先のエラーによるアラートが表示される
3. Text to generate [ja]に日本語を入力後、Enterで確定した候補内がLower underscoreでの表記のまま

---

なお、先のエラー解消後に新たに挙動が不安定な部分が現出しました。

Text to generate [ja]欄に日本語を入力中、漢字変換を確定させるためにEnterを押すとText to generate [ja]欄が消失します。

例）「詳細を入力」と入力して翻訳したい場合、「詳細を[Enter]入力」としようとすると、Enterを押した時点で翻訳を実行してText to generate [ja]が消失

**Comment by kenji-namba** [comment]
ご報告ありがとうございます。
下記の挙動ですが、検索（Ctrl+Fだっけ？) でも同じ挙動にならないでしょうか。

> Text to generate [ja]欄に日本語を入力中、漢字変換を確定させるためにEnterを押すとText to generate [ja]欄が消失します。

**Comment by wildwest-service** [comment]
> 下記の挙動ですが、検索（Ctrl+Fだっけ？) でも同じ挙動にならないでしょうか。

SublimeTextのほうの検索（Cmd+F）でしょうか。そちらのほうは毎日頻繁に使用しますが、そういえば日本語の文字列を検索することはほぼ無いですね。

事業所の端末で使用しているのですが、今週は事業所まで出ないので、週明けに確認してまたご報告させていただきますね:D

**Comment by wildwest-service** [comment]
こんにちは！ご指摘の通りSublimetext側の問題だったようで、検索で日本語を入力した際に同様の挙動を示しました。

**Comment by kenji-namba** [comment]
ありがとうございます。
Sublime textのフォーラムにも同じトピックがありました。
https://www.sublimetext.com/forum/viewtopic.php?f=2&t=12512

Sublime text、ちゃんとIME対応してくれてれば、最高なんですねどねー...
