### ISSUE TITLE
macOS Mojave + SublimeText 3.1.1での動作についいて

### ISSUE THREAD

**Issue by MasaruKitajima** [codic-project/codic-sublime-plugin#4]
良いプラグインを有難うございます。

上記環境で、日本語文字列を選択してコマンド＋Shift＋Dを押下すると、
<img width="392" alt="sublime textscreensnapz001" src="https://user-images.githubusercontent.com/3312530/48928501-f3064100-ef22-11e8-8f78-74c78b9a0299.png">
の様になり、どのレターケースを選択しても`get element`にしか変換できません。

**Comment by kenji-namba** [comment]
返信が遅くなり申し訳ございません。
最新版にて修正を行っておりますので、アップデートしてみてください。

**Comment by MasaruKitajima** [comment]
有難うございます！
無事に動作を確認できました
感謝致します。
